build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover-data test'
                coverage:
                    file: 'clover-data'
                    format: 'php-clover'
